### ISSUE TITLE
`java_version` variable not used when installing an openjdk

### ISSUE THREAD

**Issue by captain-proton** [robertdebock/ansible-role-java#12]
Think the title says everything :). I had to set the variable `java_default_version` to install the appropriate version. If I'm correct the setting for the openjdk variable come from the file `vars/main.yml`

https://github.com/robertdebock/ansible-role-java/blob/c1a376d62362d006923406425699b4c70c7e8f95/vars/main.yml#L102

## Sample Playbook

```yaml
---
- name: Get some delicious coffee
  hosts: all
  become: true

  tasks:
    - name: Bootstrap machine
      include_role: 
        name: galaxy/robertdebock.bootstrap

    - name: Java must be present
      include_role: 
        name: galaxy/robertdebock.java
      vars:
        java_vendor: openjdk
        java_type: jdk
        java_version: "8"
```

## Output

Taken from the target:

```shell
vagrant@ubuntu-focal:~$ java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

## Environment

- Control node OS: Manjaro Linux
- Control node Ansible version: 2.11.1
- Managed node OS: Ubuntu 20.04.3
