### ISSUE TITLE
Add option for JCE (Java Cryptographic Extension) for Oracle Java 8

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-java#5]
##### ISSUE TYPE
 - Feature Idea

##### OS / ENVIRONMENT
Any supported by role.

##### SUMMARY
Oracle Java 8 has a [separate piece of software to enable full encryption](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html). It should be possible for users to enable this extenstion.

##### EXPECTED RESULTS
```
- hosts: servers
  gather_facts: yes
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.java
      java_vendor: oracle
      java_version: 8
      java_jce: yes
```
